# Generated by Django 5.1.1 on 2024-11-08 20:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeck', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.AddField(
            model_name='card',
            name='answer',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='audio',
            field=models.FileField(default=None, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='card',
            name='box',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='card',
            name='question',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='card_setNumber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flashdeck.cardset'),
        ),
    ]
