# Generated by Django 5.1.1 on 2024-12-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeck', '0002_alter_card_audio_alter_card_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='card',
            name='img',
        ),
    ]
